version: "3.8"
services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      mongodb:
        condition: service_healthy  # Ensures MongoDB is fully ready
    environment:
      MONGO_URI: "mongodb://mongodb:27017"
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    restart: always
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh mongodb://localhost:27017/test --quiet
      interval: 10s
      retries: 5